version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes: 
      - ./redis/db_data:/data
  memcached:
    image: memcached
    ports:
      - "11211:11211"

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb/db_data:/data/db

  percona:
    image: percona 
    ports:
      - "3306:3306"
    volumes:
      - './percona/db_data/mysql_data:/var/lib/mysql'
      - './percona/db_data/mysql_log:/var/log/mysql'
      - './percona/conf.d:/etc/mysql/conf.d'
      # - './mnt/percona/my.cnf:/etc/mysql/my.cnf'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elastic/db_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  couchdb:
    image: couchdb
    ports: 
      - "5984:5984"
    volumes: 
      - ./couchdb/db_data:/opt/couchdb/data
  
  # riak:
  #   image: basho/riak-kv
  #   ports:
  #     - "8087:8087"
  #     - "8098:8098"
  #   environment:
  #     - CLUSTER_NAME=riakkv
  #   labels:
  #     - "com.basho.riak.cluster.name=riakkv"
  #   volumes:
  #     - ./mnt/riak/db_data:/etc/riak/schemas
  
  nginx:
    build:
      context: nginx/
    ports:
      - "18080:80"
    volumes: 
      - ./mnt/nginx/data/logs:/var/log/nginx
      - ./mnt/nginx/html:/nginx/data
      - ./mng/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links: 
      - php
  php:
    image: php:7-fpm

  # cassandra:
  #   image: cassandra
  #   ports: 
  #     - "7000:7000"
  #     - "9042:9042"
  #     - "9160:9160"
  #   volumes: 
  #     - ./mnt/cassandra:/var/lib/cassandra
  
  # mssql:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   ports:
  #     - "1433:1433"

  # cayley:
  #   image: alectolytic/cayley

  # hashiVault:
  #   image: vault
  #   ports:
  #     - "8200:8200"
  
  # hashisConsul:
  #   image: consul
  #   ports:
  #     - "8301:8301"

  # dnsmasq:
  #   image: andyshinn/dnsmasq
  #   ports:
  #     - "53:53/udp"
  #     - "53:53"

  # ejabberd:
  #   image: ejabberd
  #   ports: 
  #     - "5222:5222"
  #     - "5269:5269"
  #     - "5280:5280"
  #   build:
  #     args:

networks:
  elk:
    driver: bridge
