version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes: 
      - ./redis/db_data:/data
      
  memcached:
    image: memcached
    ports:
      - "11211:11211"

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb/db_data:/data/db

  percona:
    image: percona
    ports:
      - "3306:3306"
    volumes:
      - './percona/db_data/mysql_data:/var/lib/mysql:rw'
      - './percona/db_data/mysql_log:/var/log/mysql:rw'
      - './percona/conf.d:/etc/mysql/conf.d:rw'
      # - './mnt/percona/my.cnf:/etc/mysql/my.cnf'
    environment: 
      - MYSQL_ROOT_PASSWORD=root

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - './elasticsearch/db_data:/usr/share/elasticsearch/data'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx768m -Xms768m"
    networks:
      - elk
      
  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  # apm:
  #   build: 
  #     context: elastic-apm-server/
  #   ports:
  #     - 8200:8200

  couchdb:
    image: couchdb
    ports: 
      - "5984:5984"
    volumes: 
      - ./couchdb/db_data:/opt/couchdb/data:rw
  
  # couchbase:
  #   image: couchbase/server
  #   ports: 
  #     - "8091:8091"

  # logstash:
  #   build:
  #     context: logstash/
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx512m -Xms512m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  # nginx:
  #   build:
  #     context: nginx/
  #   ports:
  #     - "9080:8080"
  #   volumes: 
  #     - ./nginx/logs:/var/log/nginx
  #     - ./nginx/data:/nginx/data
  #     - ./nginx/sites:/etc/nginx/sites-enabled
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks: 
  #     - elk
  #   links: 
  #     - php
  # php:
  #   image: php:7-fpm
  #   ports: 
  #     - 9000:9000

  # riak:
  #   image: basho/riak-kv
  #   ports:
  #     - "8087:8087"
  #     - "8098:8098"
  #   environment:
  #     - CLUSTER_NAME=riakkv
  #   labels:
  #     - "com.basho.riak.cluster.name=riakkv"
  #   volumes:
  #     - ./riak/db_data:/etc/riak/schemas

  # cassandra:
  #   image: cassandra
  #   ports: 
  #     - "7000:7000"
  #     - "9042:9042"
  #     - "9160:9160"
  #   volumes: 
  #     - ./cassandra:/var/lib/cassandra
  
  # mssql:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   ports:
  #     - "1433:1433"

  # cayley:
  #   image: alectolytic/cayley

  # hashiVault:
  #   image: vault
  #   deploy:
  #     restart_policy:
  #       condition: any
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #   ports:
  #     - "18200:8200"
  
  # hashisConsul:
  #   image: consul
  #   ports:
  #     - "8301:8301"

  # dnsmasq:
  #   image: andyshinn/dnsmasq
  #   ports:
  #     - "53:53/udp"
  #     - "53:53"

  # ejabberd:
  #   image: ejabberd
  #   ports: 
  #     - "5222:5222"
  #     - "5269:5269"
  #     - "5280:5280"
  #   build:
  #     args:

networks:
  elk:
    driver: bridge
