version: '2'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"

  percona:
    image: percona 
    ports:
      - "3306:3306"
  couchdb:
    image: couchdb
    ports: 
      - "5984:5984"

  cassandra:
    image: cassandra
    ports: 
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"

  # cayley:
  #   image: alectolytic/cayley

  hashiVault:
    image: vault
    ports:
      - "8200:8200"
  
  hashisConsul:
    image: consul
    ports:
      - "8301:8301"

  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/udp"
      - "53:53"

  # ejabberd:
  #   image: ejabberd
  #   ports: 
  #     - "5222:5222"
  #     - "5269:5269"
  #     - "5280:5280"
  #   build:
  #     args:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
